filter:
    path: [ src/*]
    excluded_path: [vendor/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    php_analyzer: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor]
